Repository widgetbook/widgetbook-demo, pull requests merged in 2023-02, with the labels that each got.

#70 ci: :arrow_up: bump CLI version
  .github/workflows/upload-review.yml
Labels: dependencies, github_actions

#69 chore: :arrow_up: bump dependencies
  app_widgetbook/lib/app.widgetbook.dart
  app_widgetbook/pubspec.lock
  app_widgetbook/pubspec.yaml
Labels: dependencies

#74 feat: :sparkles: add design links for `ExpandedTweet`
  .github/workflows/upload-build.yml
  .github/workflows/upload-review.yml
  app_widgetbook/lib/core/tweet/expanded_tweet.dart
Labels: enhancement

#75 feat: design link for `Avatar`
  .github/workflows/upload-build.yml
  .github/workflows/upload-review.yml
  app_widgetbook/lib/core/user/avatar.dart
Labels: enhancement

#76 ci: codemagic
  codemagic.yaml
Labels: enhancement

#78 ci: :green_heart: change back to stable flutter channel
  .github/workflows/upload-build.yml
  .github/workflows/upload-review.yml
Labels: github_actions
